### ISSUE TITLE
assert norm_scale.mean() == 300 in the DTU

### ISSUE THREAD

**Issue by zhirui-gao** [google-research/sparf#1]
I use dtu dataset, but  norm_scale equal to [324.6,324.6,324.6].

**Comment by PruneTruong** [comment]
Hi, 

Are you using the same scenes as me? And the data from pixelNeRF? 

I had added this because in all the scenes that I trained/evaluated on, the norm_scale was always 300, so I hardcoded it in 'self.scaling_factor = 1./300. ', so i could directly use this argument to rescale the translation vectors and the depths accordingly. However, if you're using scenes for which this norm_scale is different, it could easily be modified such as self.scaling_factor = 1./norm_scale on the scene.

**Comment by zhirui-gao** [comment]
Thanks a lot!
